name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      # Extract version from tag
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      # Create the release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed

            See the [changelog](https://github.com/${{ github.repository }}/compare/${{ github.ref_name }}...${{ github.ref_name }}) for details.

            ## Installation

            ```bash
            pip install zoomcutter==${{ steps.get_version.outputs.VERSION }}
            ```

            Or use with uvx:

            ```bash
            uvx zoomcutter@${{ steps.get_version.outputs.VERSION }}
            ```
